### ISSUE TITLE
Wont show relationship when viewing recouce

### ISSUE THREAD

**Issue by timsamuelsson** [Benjacho/belongs-to-many-field-nova#10]
Hello,

Is your package suposed to show the relationship in the index view? Or should i use a computed field?

**Comment by Benjacho** [comment]
Hello, you can make a pr with that functionality or use computed field. The field does not have that feature.

**Comment by timsamuelsson** [comment]
Thank you!

Im still a nova Noob but a computed field solved it :)

I was mostly wondering if i was doing something wrong..

Thank you!

//Tim

**Comment by Benjacho** [comment]
Keep training with nova is beautiful!

**Comment by timcv** [comment]
Hi, pull request #17 would fix this.

**Comment by Benjacho** [comment]
Amazing work!
