### ISSUE TITLE
Error on "optional" field. 

### ISSUE THREAD

**Issue by mikoop79** [Benjacho/belongs-to-many-field-nova#11]
hi @Benjacho. This is a great package for nova. 

I wonder if this is supposed to happen. not sure but the if I save a product and dont select the belongstomany field It throws this error.  this field is optional for me.  does it have to have data? 

![image](https://user-images.githubusercontent.com/971122/63513929-c66f6c00-c52a-11e9-88e8-2758498addd3.png)

**Comment by Benjacho** [comment]
Please can you share your code, please?

**Comment by chaduvulasureshreddy** [comment]
While we are using BelongsToManyField inside of NovaDependencyContainer
if NovaDependencyContainer will false, while submit BelongsToManyField  going null values at that time  we are getting this issue

<img width="959" alt="issue" src="https://user-images.githubusercontent.com/33175480/64757813-c1fa0a00-d550-11e9-996e-335caa5da915.png">

**Comment by Benjacho** [comment]
Hey! i think it is solved in new release!
