### ISSUE TITLE
Nova 4 support

### ISSUE THREAD

**Issue by inventionate** [Benjacho/belongs-to-many-field-nova#110]
Any plan about support for Laravel Nova 4? Anyway, thank you for your great work!

**Comment by OsTheNeo** [comment]
estoy adaptando este paquete para nova4 , https://novapackages.com/packages/ostheneo/nova-fields , si alguien quiere ayudar, bienvenido

**Comment by Benjacho** [comment]
@inventionate support for Nova 4 and a roadmap was added, if you want to contribute you are free to do it!
