### ISSUE TITLE
pivot create and update

### ISSUE THREAD

**Issue by anditsung** [Benjacho/belongs-to-many-field-nova#15]
im creating a pivot for material usage

```
public function usages() : BelongsToMany
    {
        return $this->belongsToMany(MaterialUsage::class, 'materials_usages', 'material_id', 'material_usage_id');
    }
```

when i add it the created_at and updated_at is null.
how to add the datetime?

--add
how to show it on detail?

**Comment by Benjacho** [comment]
i am not sure but this package actually does not support pivot attributes, with a PR we can do it!
