### ISSUE TITLE
How to use with spatie/translate

### ISSUE THREAD

**Issue by webparadoxer** [Benjacho/belongs-to-many-field-nova#16]
```
 $financeArray = [];
        foreach (\App\Model\FinanceType::all() as $entityType) {
            $type = new \stdClass();
            $type->id = $entityType->id;
            $type->name = $entityType->name;
            $financeArray[] = $type;
        }
            BelongsToManyField::make('AdvertFinance', 'finance', 'App\Nova\AdvertFinance')->options($financeArray),
```

All ok on create, but in update i see like this
![image](https://user-images.githubusercontent.com/5503366/66779583-340a9980-eed7-11e9-944a-4ff44f00b57a.png)
How to resolve this?!

**Comment by Benjacho** [comment]
You can use optionsLabel() function if you want to display bases on one language.
This package does not support multi languages now but you can make a PR for this or I can help you to do it!

**Comment by webparadoxer** [comment]
Can an example please how to do in my case.
            BelongsToManyField::make('AdvertFinance', 'finance', 'App\Nova\AdvertFinance')->options($financeArray)->optionsLabel("name->tr") or
            BelongsToManyField::make('AdvertFinance', 'finance', 'App\Nova\AdvertFinance')->options($financeArray)->optionsLabel("name"), wrong

**Comment by webparadoxer** [comment]
And, can I use closure in options?
Like this
```
BelongsToManyField::make('AdvertFinance', 'finance', 'App\Nova\AdvertFinance')->options(function() {
$financeArray = [];
foreach (\App\Model\FinanceType::all() as $entityType) {
$type = new \stdClass();
$type->id = $entityType->id;
$type->name = $entityType->name;
$financeArray[] = $type;
}
return $financeArray;
})
```

**Comment by webparadoxer** [comment]
??

**Comment by Benjacho** [comment]
Hello you can test it!, optionsLabel('tr') is correct

**Comment by webparadoxer** [comment]
![image](https://user-images.githubusercontent.com/5503366/66931473-d002e500-f03e-11e9-954e-069c021babca.png)
                BelongsToManyField::make('AdvertFinance', 'finance', 'App\Nova\AdvertFinance')->options($financeArray)->optionsLabel('tr'),

**Comment by webparadoxer** [comment]
no text(

**Comment by webparadoxer** [comment]
please help)

**Comment by Benjacho** [comment]
Okay, please send me yur options in array of objects format please

**Comment by devilstars** [comment]
Same here. 

```
BelongsToManyField::make('Category', 'category', 'App\Nova\Category')
                ->options(\App\Category::all())
                ->optionsLabel('title')->rules('min:1', 'max:1', 'required'),
```

Shows like this:
![2019-10-21_151122](https://user-images.githubusercontent.com/12907959/67203942-14163100-f415-11e9-8a5b-7078afbb837c.png)

**Comment by Benjacho** [comment]
Ok i understood you need to pluck id and title

**Comment by Benjacho** [comment]
what is the package that are you using?

**Comment by devilstars** [comment]
`spatie/translate`

**Comment by devilstars** [comment]
nvm, I've managed to make it work

Field:
```php
BelongsToManyField::make('Team', 'team', 'App\Nova\Team')
    ->options(\App\Team::getCleanName())
    ->optionsLabel('title')->rules('min:1', 'max:1', 'required'),
```

Team model:
```php
public static function getCleanName($columns = ['*'])
{
    app()->setLocale('uk');
    return static::query()->select('id', 'name->uk as title')->get(
        is_array($columns) ? $columns : func_get_args()
    );
}
```

**Comment by webparadoxer** [comment]
Nice, but why u change current locale and return only in one locale!

**Comment by devilstars** [comment]
my Nova's locale is "uk" (Ukraine).
