### ISSUE TITLE
Issue with optionsLabel in detailed view 

### ISSUE THREAD

**Issue by chaduvulasureshreddy** [Benjacho/belongs-to-many-field-nova#18]
With passing **optionsLabel** its working in add and update, because  their the below code writen

**this.optionsLabel = this.field.optionsLabel ? this.field.optionsLabel : 'name';**

But in detailed view Means **DetailField.vue** file directly written 
**{{resource.name}}**

Because of the above line while i am passing **optionsLabel** its showing empty

**Comment by Benjacho** [comment]
Try this in your model, ex: optionsLabel('title') 
`
class ABC extends Model {
 protected $appends = [
'name'
]

public function getNameAttribute()
{
 return $this->title;
}
}
`

**Comment by chaduvulasureshreddy** [comment]
Its working,  Thanks @Benjacho
