### ISSUE TITLE
Error when updating

### ISSUE THREAD

**Issue by noahlocke** [Benjacho/belongs-to-many-field-nova#19]
```php
BelongsToManyField::make('Services', 'services', 'App\Nova\Service')
  ->rules('min:1','max:1','required')
  ->options(\App\Service::whereHas('counties', function ($q) 
    {
      $q->where('county_id', $this->county_id);
    }
)->get())
```

When I `create` a resource, the field correctly creates the relationships, however when I attempt to `edit` and `update` a resource it appears that Nova is trying to set a value on a column rather than sync the attached relationships:

Error:

SQLSTATE[42S22]: Column not found: 1054 Unknown column `services` in 'field list' (SQL: update `notes` set `has_notes` = 0, `services` = ?, `notes`.`updated_at` = 2019-10-22 21:40:12 where `id` = 557)"

**Comment by Benjacho** [comment]
I will see it

**Comment by noahlocke** [comment]
@Benjacho were you able to recreate?

**Comment by Benjacho** [comment]
what version are ou using?

**Comment by noahlocke** [comment]
@Benjacho v1.2.1

**Comment by noahlocke** [comment]
@Benjacho This turned out to be an issue with another package! Closing this issue :)
