### ISSUE TITLE
IndexField.vue Link not absolute

### ISSUE THREAD

**Issue by cfreak** [Benjacho/belongs-to-many-field-nova#20]
The Link which is generated in the IndexField.vue is not absolute, this causes problems if you link it into another resource.

For Example i have 

 /admin/resources/usages/1 <-- See Screenshot

If i click on a usage listet in the table, i get the url /admin/resources/usages/usages/2 which ends up in an 404.

![Bildschirmfoto 2019-10-31 um 08 40 25](https://user-images.githubusercontent.com/202342/67927939-1ec18a80-fbba-11e9-84ba-137a505c6110.png)

Can you somehow fix that?

**Comment by Benjacho** [comment]
Update your package! This was fixed on 1.1

**Comment by cfreak** [comment]
Sorry i'm using 1.2 and it is not fixed yet.

**Comment by Benjacho** [comment]
I think it is fixed on 1.2.1

**Comment by timcv** [comment]
It might be fixed the pull request (#21) I just made :)
