### ISSUE TITLE
MorphedByMany Support

### ISSUE THREAD

**Issue by bigperson** [Benjacho/belongs-to-many-field-nova#23]
I would like use this package for MorphedByMany field. Is it possible?

**Comment by Benjacho** [comment]
Could you please recreate business logic of MorphedByMany, to implement this feature

**Comment by bigperson** [comment]
@Benjacho 
I have  models and resources Tag, News, Post.
Tag can be attached to News and to Post, use MorphedByMany relation

See https://nova.laravel.com/docs/2.0/resources/relationships.html#morphtomany
and https://laravel.com/docs/6.x/eloquent-relationships#many-to-many-polymorphic-relations

**Comment by Benjacho** [comment]
Hello, did you reach something?

**Comment by bigperson** [comment]
no... :(
