### ISSUE TITLE
Soporte para Pivot

### ISSUE THREAD

**Issue by demency** [Benjacho/belongs-to-many-field-nova#3]
Hola Benjamín

Muchas gracias por desarrollar el paquete, te quería consultar si tienes alguna idea de como manejar los datos que vienen en los pivot?

**Comment by Benjacho** [comment]
Hola para manejar los datos que vienen en los pivot puedes hacer un scope y si ves le puedes pasar las opciones que desees en options() ahi puedes hacer una function anonima sino dame un ejemplo :)
