### ISSUE TITLE
Press enter to create tag doesn't work

### ISSUE THREAD

**Issue by abr4xas** [Benjacho/belongs-to-many-field-nova#30]
Hi there, I'm using this package to select one or many categories but also I want to create a new one if doesn't exist but this doesn't work:

![image](https://user-images.githubusercontent.com/405484/78195764-d81cd880-7456-11ea-8f7a-1c9fcdf44721.png)

This is my config:

![code](https://user-images.githubusercontent.com/405484/78195851-0ef2ee80-7457-11ea-80ac-bfbcd1d9a80c.png)

**Comment by Benjacho** [comment]
This package does not support this feature, please make PR with this feature
