### ISSUE TITLE
Add "searchable" behavior

### ISSUE THREAD

**Issue by jdvrpcre** [Benjacho/belongs-to-many-field-nova#33]
Hello,
First, thank you. It is a very useful nova module.

For very long lists of options, is it possible to add a "searchable" behavior which relaunches the ajax request when we change the search query.

By doing so, we can limit the results using relatableQuery and inspecting the request parameters.

Best regards.

**Comment by Benjacho** [comment]
Hello, i think that is possible. You can make a PR for that feature
