### ISSUE TITLE
No Error Message Visible

### ISSUE THREAD

**Issue by estebanav** [Benjacho/belongs-to-many-field-nova#37]
Hi @Benjacho ,

We are using belongs-to-many-field version 1.7, and even the error is coming in the response of the service it is not being shown in the component. Here is an screenshot of the issue:

![Screenshot from 2020-06-04 20-27-04](https://user-images.githubusercontent.com/803435/83820218-69503b80-a6a2-11ea-94f8-59299cec51bd.png)

Is this an bug of this version?
Thanks,
E.

**Comment by Benjacho** [comment]
i Think this is a bug on all versions right now, Let's see

**Comment by styxit** [comment]
I am having the same problem

**Comment by Benjacho** [comment]
Yes, sorry guys i do not have time to fix this, if anyone of you can do it please do it! thanks in advance

**Comment by luigel** [comment]
@Benjacho i think #51 is not included in the latest version of the package.
