### ISSUE TITLE
Soporte para nova 2.0

### ISSUE THREAD

**Issue by demency** [Benjacho/belongs-to-many-field-nova#4]
Por algún motivo el paquete lanza un error:

`Argument 3 passed to Laravel\Nova\Fields\Field::__construct() must be callable or null, string given, called in /mnt/c/Users/ianto/Code/despachosv2/nova/src/Element.php on line 46`

Por lo que infiero que se debe a que no soporta la versión 2.0 de nova.

**Comment by drsdre** [comment]
You probably need to add the following _construct to src/BelongsToManyField.php:

```
    /**
     * Create a new field.
     *
     * @param  string  $name
     * @param  string|null  $attribute
     * @param  string|null  $resource
     * @return void
     */
    public function __construct($name, $attribute = null, $resource = null)
    {
        parent::__construct($name, $attribute);
    }
```

**Comment by Benjacho** [comment]
@drsdre amazing code! Ty

**Comment by Benjacho** [comment]
@demency this is solved in version 0.4
