### ISSUE TITLE
Create button and attach form for Belongstomany relationship

### ISSUE THREAD

**Issue by thiname** [Benjacho/belongs-to-many-field-nova#45]
Hi there !
I'm searching a fix for our Nova App. I have a relationship belongstomany between Minute and Stakeholder in which I have a pivot.
I would love to have attach or create  belongstomany relationship as shown in my screenshots :
1. A searching field to attach stakeholders to my minute
![attach-stakeholder](https://user-images.githubusercontent.com/33346555/89789298-b0363380-db20-11ea-8518-f41a58b63e2a.jpg)
2. A create button to create new stakeholder with a modal window
![create-stakeholder](https://user-images.githubusercontent.com/33346555/89789306-b1fff700-db20-11ea-8b08-e3295ec6a7ef.jpg)
As we have for for one level deep relationship (belongsto)
We already found this following resources but they are not satisfaying for our users :
https://github.com/dillingham/nova-attach-many (because we have to many resources to list and we can only attach not create)
https://novapackages.com/packages/yassi/nova-nested-form (we can only create not attach)
https://novapackages.com/packages/benjacho/belongs-to-many-field (we can only attach)
Would you be available to develop this feature ? If yes what could be your expectation ?

**Comment by Benjacho** [comment]
That would be a great feature for this package, i am available to develop this feature, please send a mail to christianbfc97@gmail.com with your expectations.
