### ISSUE TITLE
How can I specify the pivot table name?

### ISSUE THREAD

**Issue by Peterragheb** [Benjacho/belongs-to-many-field-nova#47]
I want to specify the pivot table name. by default it filters from the field table.
Is there a way to set the pivot table name through setPivot() method?

For example:
```
 BelongsTo::make('Association', 'association', 'App\Nova\Association'),

 BelongsToManyField::make('Participants', 'participant', 'App\Nova\Participant')
     ->dependsOn('association', 'association_id'),
```
It tries to search for `association_id` column in the `participant` table. Shouldn't it try to search for that column in `assocation_participant` table?

**Comment by Benjacho** [comment]
Yes it tries because it means that participant dependsOn association, maybe a method that you can contribute could be dependsOnRelation('association', 'association_id') that searches in many to many relationship table.

**Comment by deepraj-sinha** [comment]
Is there any method dependsOnRelation ?? @Benjacho or any way to do this?

**Comment by Benjacho** [comment]
There is a dependsOn method that you can hack
