### ISSUE TITLE
Translatable Fields

### ISSUE THREAD

**Issue by SimonBarrettACT** [Benjacho/belongs-to-many-field-nova#48]
I have an issue where I am trying to attach multiple records where the 'name' for each record is a translatable field (I'm using [spatie/laravel-translatable](https://github.com/spatie/laravel-translatable)).

When the records are displayed, the json for the fields is being displayed, not the translated names.

![](https://user-images.githubusercontent.com/57679318/90631799-46521400-e21b-11ea-9ad3-b23916d5e56b.png)

**Comment by Benjacho** [comment]
You can check this #40, also don't forget to comment if it works to merge this.

**Comment by SimonBarrettACT** [comment]
I tried the following:

 BelongsToManyField::_make_('Towns', 'towns', 'App\\Nova\\Town')->optionsLabel('name.en')

but now nothing is displayed in the field.

![](https://user-images.githubusercontent.com/57679318/91196064-99cbd280-e6f1-11ea-9deb-a0fdc75648c6.png)

**Comment by Benjacho** [comment]
Solved!
