### ISSUE TITLE
"Unresolvable dependency resolving [Parameter #0 [ <required> $resource ]] in class Laravel\Nova\Resource"

### ISSUE THREAD

**Issue by terasupernova** [Benjacho/belongs-to-many-field-nova#5]
Hi, when i create the new record with multi select then this error pop up.
`"Unresolvable dependency resolving [Parameter #0 [ <required> $resource ]] in class Laravel\Nova\Resource"`

<img width="1112" alt="Screen Shot 2019-05-31 at 11 43 59 AM" src="https://user-images.githubusercontent.com/8252838/58680245-8bc9bd80-8399-11e9-9198-0cacf8487da8.png">

Did I miss out anything? Please help.
Thank you very much.

**Comment by Benjacho** [comment]
can you send me your code?

**Comment by terasupernova** [comment]
Hi @Benjacho thanks for the reply. The issue is solved. 
Thanks.

**Comment by adeel-at-cierra** [comment]
@Benjacho I am facing this same issue will you let me know what was the issue ?

**Comment by miracsengonul** [comment]
> @terasupernova Hi, can you explain how you solved it. I'm having the same issue. Please reply. Thanks

You should check your `use` Model path. It mustn't be `App\Nova\XXX;` 
Must be `App\Models\XXX;` instead
