### ISSUE TITLE
Utilizar información en evento created

### ISSUE THREAD

**Issue by alejandrosanchez18** [Benjacho/belongs-to-many-field-nova#6]
Al agregar este field en una relación y utilizar un observer de la clase asociada en el evento created solo llega un array vacío de la relación.
Tengo la clase User y una clase Product que tienes una relación de muchos a muchos. 
Al crear un nuevo User agregando el field de BelongsToMany con Product, en el evento created recibo solo un array vacío de products. Las tables y la relación se crea correctamente pero necesito ejecutar un evento cuando se crea un nuevo User utilizando los Product que le corresponden al user.

Alguna sugerencia?

**Comment by Benjacho** [comment]
Hola, no se esta creando, actualizando o etc. No hay evento para lo que se hace que es el metodo Sync asi que en un Observer no podras hacerlo, te recomiendo que hagas un trait que extienda del que se tiene uses ese para poder ejecutar el codigo que necesitas.
