### ISSUE TITLE
relation route return 401 unauthorized

### ISSUE THREAD

**Issue by meyer59** [Benjacho/belongs-to-many-field-nova#63]
Hi
I followed the instrctions in the readme to install and configure the package but i am unable to make it work. 
The route for fetching the select data is returning a 401 unauthorized i don't know why. Here is the screenshot of the error:
![image](https://user-images.githubusercontent.com/9505463/100750078-d2accf00-33e5-11eb-9ec7-c34d6119ca2d.png)

Here is my code for implementing the plugin in nova:
`            BelongsToManyField::make('the Apps','appTypes', AppTypeResourceNova::class)->optionsLabel('id'),
`
Do you guys have an idea why this is returning 401 ?
Thanks

**Comment by Benjacho** [comment]
Are you applying some policies or overwriting authrorizing methods?
