### ISSUE TITLE
Missing validation error message

### ISSUE THREAD

**Issue by timcv** [Benjacho/belongs-to-many-field-nova#66]
Hi,

I updated my Laravel from 6->8 and Nova from 2->3 and now the validation messages for BelongsToManyField has disappeared. Nova still shows the message: "There was a problem submitting the form" and the correct response data:

```
{
  "message":"The given data was invalid.",
  "errors":{
    "end_user":["The End user field is required."],
    "countries":["The countries field is required."]
  }
}
```

![Skärmavbild 2021-01-13 kl  14 04 22](https://user-images.githubusercontent.com/1415514/104456427-ed5b9180-55a8-11eb-9d59-d9be6c90d6c8.png)

```
BelongsToManyField::make('Countries', 'countries', Country::class)
    ->rules('required'),
```

**Comment by chrismeistre** [comment]
I am experiencing the same issue

**Comment by chrismeistre** [comment]
@timcv not sure if you saw this, but I just came across the following, and it works if I do the edit manually https://github.com/Benjacho/belongs-to-many-field-nova/pull/51/files

Hopefully a package release comes soon

**Comment by timcv** [comment]
@chrismeistre I wrote him a private message on Twitter 14 jan about that, without answer.
Maybe he have to much work right now...

**Comment by Benjacho** [comment]
It should be solved
