### ISSUE TITLE
Use as single select

### ISSUE THREAD

**Issue by OliverZiegler** [Benjacho/belongs-to-many-field-nova#68]
With the new option to set pivot attribtues we have a nice possibility to use this field as a single select by using 
`setMutliselectProps` with `multiple => false`.

Unfortunately the field then saves nothing as Vue-Multiselect returns no array but the single selected object.
Any Idea how this could be achieved is highly appreciated.

**Comment by Benjacho** [comment]
Yes, you can check on how is implemented on the front side to enable that feature please.
