### ISSUE TITLE
Support JSON columns (spatie/laravel-translatable)

### ISSUE THREAD

**Issue by RomkaLTU** [Benjacho/belongs-to-many-field-nova#72]
Need support for translations based on JSON serialization, for example when the title column is JSON output is:

`{ "en": "", "lt": "Odontologija", "ru": "" }{ "en": "", "lt": "Periodontologija", "ru": "" }{ "en": "", "lt": "Implantacija", "ru": "" }`

Should be something like this:

`->optionsLabel('title.en')`

As a temporary solution, I made a custom setter in the model.

**Comment by RomkaLTU** [comment]
Ups doesn't work with model getters either.

**Comment by Benjacho** [comment]
Solved!
