### ISSUE TITLE
Rules required not working?

### ISSUE THREAD

**Issue by terasupernova** [Benjacho/belongs-to-many-field-nova#8]
Hi, please see the code below. The rules required is not working?
Please help, thanks.

`BelongsToManyField::make('Main Categories', 'mainCategories', 'App\Nova\MainCategory')
                ->options(\App\Models\MainCategory::get(['id', 'name']))
                ->relationModel(\App\Models\MainCategory::class)->rules('required'),`

**Comment by Benjacho** [comment]
Rules are not implemented in this package, i will do in next releases as it needed

**Comment by Benjacho** [comment]
Hey i already implemented rules and custom rules! you can see in version 0.5

**Comment by terasupernova** [comment]
@Benjacho 
Thanks for the fast reply. 
Work perfectly. Thanks

**Comment by noahlocke** [comment]
@terasupernova @Benjacho validation does not appear to work at all in version 0.7?

**Comment by noahlocke** [comment]
@terasupernova @Benjacho never mind, I'm wrapping the field in `epartment/nova-dependency-container` and it's breaking the validation. I removed the wrapper and it works perfectly!
