### ISSUE TITLE
getHelpText does not exist

### ISSUE THREAD

**Issue by thibodelanghe** [Benjacho/belongs-to-many-field-nova#84]
Hi, 

Since the package update to v1.9 a bug is introduced. 

When trying to edit a nova resource, the following error appears 
`Method Benjacho\BelongsToManyField\BelongsToManyField::getHelpText does not exist. {"userId":1,"exception":"[object] (BadMethodCallException(code: 0): Method Benjacho\\BelongsToManyField\\BelongsToManyField::getHelpText does not exist.` 

Downgrading to v1.8 does temp fix it

**Comment by mraddatz** [comment]
Same here

**Comment by diogocnunes** [comment]
Same here

**Comment by Benjacho** [comment]
Hey both of you please upgrade your laravel nova version.

**Comment by RicLeP** [comment]
For anyone with this issue get make sure you use version 1.7.0. 1.8.0 is a breaking change on older versions of Nova.
