### ISSUE TITLE
identificador con nombre diferente 

### ISSUE THREAD

**Issue by hufex** [Benjacho/belongs-to-many-field-nova#9]
Hola Te expongo mi caso 
tengo la tabla user y la tabla de turnos, por mala oganizacion los id's tiene nombres diferentes. 
user ( id), turno(id_turnos)  la relacion usuario_turnos(id_usuario, id_turno) . 

lo que detecte es que se esta esperando siempre el campo 'id'
`$values = array_column(json_decode($request->$attribute, true),'id');`
por lo que no me permite insertar los valores. 

la solucion que encontre fue agregar un nuevo atributo  
`public $attributeId = 'id';`
y una nueva función  
`    public function setAttributeId($attributeId='id'){
        $this->attributeId= $attributeId;
        return $this;
    }`
y modificar esta linea para que quede de esta manera 
`$values = array_column(json_decode($request->$attribute, true),$this->attributeId);`

me parece genial tu  trabajo, saludos espero sea de utilidad y si hay otra manera diferente de resolver el detalle , me gustaría saber 

Saludos Cordiales.

**Comment by Benjacho** [comment]
Hola Hufex muchas gracias, por lo general se usa 'id', pero tu resolviste tu caso de una muy buena forma, saludos. Podrias cambiar ya que es un string y no una variable a 'id_turnos' si los turnos tiene esos id's
