### ISSUE TITLE
Rules are not respected

### ISSUE THREAD

**Issue by mnlmaier** [Benjacho/belongs-to-many-field-nova#90]
Hi guys,

I have this code: 
`BelongsToManyField::make('Values', 'values', 'App\Nova\Value')->rules('required', 'min:1', 'max:5', 'size:3'),` 

Still i can attach more than 5 values, also, the "required" property is not respected. Am I missing something here?

**Comment by mnlmaier** [comment]
bump

**Comment by Benjacho** [comment]
This actually works, update your version or check nova core specific.
